cp 3-paper-names.tex revised-submission/
cp ../results/plane/pareto-plane-iso-best-balanced-legend-viz-10-fontsize_pareto_SD.pdf revised-submission/figures/
cp ../results/correlations/figures/correlations-curve-whiteaxis-bw.pdf revised-submission/figures/
cp ../results/correlations/figures/posteriors/posterior_Real_*.pdf revised-submission/figures/
cp ../results/correlations/figures/posteriors/posterior_Efficiency_*.pdf revised-submission/figures/
cp everything_mainPaper.bib revised-submission/
cp figures/corr-full.png revised-submission/figures/
cp figures/grammar-langs-fontsize-friends-rect.png revised-submission/figures/
cp pnas-new.cls revised-submission/
cp pnas-new.bst revised-submission/
cp pnasresearcharticle.sty revised-submission/
